### ISSUE TITLE
Questions about reproducing your experiment and getting the exact experimental results

### ISSUE THREAD

**Issue by xndong** [ebagdasa/backdoor_federated_learning#13]
I pull your source code from github and try to experiment it, but I did not get a good experimental results.  

___Test Target_ResNet_18 poisoned: False, epoch: 5: Average loss: 2.3041, Accuracy: 1001/10000 (10.0100%)
Done in 6.461248397827148 sec.

After every epoch，it always get "Accuracy: 1001/10000 (10.0100%)"

I hope you don’t mind my asking, and could you please give me some general instructions step by step and all the parameter settings in params.yaml for your experiments in your paper.

**Comment by TudouJack** [comment]
>Maybe you should run with params_runner.yaml. The fixed accuracy(10%) means your model is a All-One Matrix.

**Comment by TudouJack** [comment]
Hello. Can you please answer one question for me? Do you know why this code is removing the backdoor data? 

`

range_no_id = list(range(50000)) 
for image in self.params['poison_images'] + self.params['poison_images_test']: 
        if image in range_no_id: 
            range_no_id.remove(image) 

`

The code above is at line 103 in the  backdoor_federated_learning/image_helper.py.
Thank you for your help.

**Comment by ebagdasa** [comment]
hey, @xndong sorry again for your problems, I don't support this code anymore and understand the frustration, I think it might be much easier to reproduce the results with newer FL frameworks.

**Comment by ebagdasa** [comment]
@TudouJack so you don't train on images with correct labels that are part of the poisoned dataset.
