### ISSUE TITLE
The poisoned dataset.

### ISSUE THREAD

**Issue by TudouJack** [ebagdasa/backdoor_federated_learning#14]
Hello. Can you please answer one question for me? Do you know why this code is removing the backdoor data?

`

range_no_id = list(range(50000))
for image in self.params['poison_images'] + self.params['poison_images_test']:
if image in range_no_id:
range_no_id.remove(image)

`
The code above is at line 103 in the backdoor_federated_learning/image_helper.py.

And in train.py, the adversary should change the poisoned data's label. If poisoned_data ( = helper.poisoned_data_for_train) has removed those specific images, like green cars, cars with racing stripes and cars with vertically striped walls in the background, how do the adversary change the labels of that specific images?
![image](https://user-images.githubusercontent.com/47101111/164029817-a8d0f5d2-f2c4-4d11-bdcd-f43dc805ab33.png)

Thank you for your help.

**Comment by ebagdasa** [comment]
it's the last line in your screenshot that changes the label
