### ISSUE TITLE
Corpus parsed dataset seems to have expired

### ISSUE THREAD

**Issue by cjrcjrdl1** [ebagdasa/backdoor_federated_learning#21]
Thank you for providing us with a good code.

The link in Corpus parsed dataset seems to have expired at this time.

Can you upload it again?

**Comment by C-andour** [comment]
请问你解决了这个问题了吗？

**Comment by cjrcjrdl1** [comment]
Yes
You should modify the utils/words.yaml file as follows

recreate_dataset: false -> recreate_dataset: true

**Comment by cjrcjrdl1** [comment]
> 请问你解决了这个问题了吗？

Yes
You should modify the utils/words.yaml file as follows

recreate_dataset: false -> recreate_dataset: true

**Comment by tangfire** [comment]
> > 请问你解决了这个问题了吗？
> 
> Yes You should modify the utils/words.yaml file as follows
> 
> recreate_dataset: false -> recreate_dataset: true

按照你的方法，把recreate_dataset: false -> recreate_dataset: true，但还是报错:
![image](https://github.com/user-attachments/assets/46026c44-f706-4b0b-8c34-b54d8ac3488f)

**Comment by dongdongzhaoUP** [comment]
> > > 请问你解决了这个问题了吗？
> > 
> > 
> > Yes You should modify the utils/words.yaml file as follows
> > recreate_dataset: false -> recreate_dataset: true
> 
> 按照你的方法，把recreate_dataset: false -> recreate_dataset: true，但还是报错: ![image](https://private-user-images.githubusercontent.com/80095598/360551065-46026c44-f706-4b0b-8c34-b54d8ac3488f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNTY0OTgsIm5iZiI6MTcyOTE1NjE5OCwicGF0aCI6Ii84MDA5NTU5OC8zNjA1NTEwNjUtNDYwMjZjNDQtZjcwNi00YjBiLThjMzQtYjU0ZDhhYzM0ODhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDA5MDk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiMGJjN2M1YjdkMTA4MzYzYjVkZGI0ZTAyNGUwMGQ0MWU4ZTUwYzM1NDY0OWNjYjE5NGQwNzBmMDVmZDRhNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PGJYIUUndd6e4cbWDF83ir2dNI-tgl6y6UkIzEqBXSg)

+1

**Comment by K1aran** [comment]
> > > > 请问你解决了这个问题了吗？
> > > 
> > > 
> > > Yes You should modify the utils/words.yaml file as follows
> > > recreate_dataset: false -> recreate_dataset: true
> > 
> > 
> > 按照你的方法，把recreate_dataset: false -> recreate_dataset: true，但还是报错: ![image](https://private-user-images.githubusercontent.com/80095598/360551065-46026c44-f706-4b0b-8c34-b54d8ac3488f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNTY0OTgsIm5iZiI6MTcyOTE1NjE5OCwicGF0aCI6Ii84MDA5NTU5OC8zNjA1NTEwNjUtNDYwMjZjNDQtZjcwNi00YjBiLThjMzQtYjU0ZDhhYzM0ODhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDA5MDk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiMGJjN2M1YjdkMTA4MzYzYjVkZGI0ZTAyNGUwMGQ0MWU4ZTUwYzM1NDY0OWNjYjE5NGQwNzBmMDVmZDRhNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PGJYIUUndd6e4cbWDF83ir2dNI-tgl6y6UkIzEqBXSg)
> 
> +1

https://github.com/ebagdasa/federated_adaptation/blob/0c0ae97445fddc635c427ae100854bc70a00a11c/README.md?plain=1#L19

**Comment by Shixiong-Li** [comment]
> > > 请问你解决了这个问题了吗？
> > 
> > 
> > Yes You should modify the utils/words.yaml file as follows
> > recreate_dataset: false -> recreate_dataset: true
> 
> 按照你的方法，把recreate_dataset: false -> recreate_dataset: true，但还是报错: ![image](https://github.com/user-attachments/assets/46026c44-f706-4b0b-8c34-b54d8ac3488f)

请问你解决了吗？
