### ISSUE TITLE
corpus database

### ISSUE THREAD

**Issue by 2524434293** [ebagdasa/backdoor_federated_learning#26]
Does anyone have this corpus database？Could you please send me a copy? Thx. My email address is: [2524434293@qq.com](mailto:2524434293@qq.com)

**Comment by xingyushu** [comment]
> Does anyone have this corpus database？Could you please send me a copy? Thx. My email address is: [2524434293@qq.com](mailto:2524434293@qq.com)

did you get the dataset

**Comment by 2524434293** [comment]
sorry，I didn’t get. You can give me a copy if you get it. Thanks 🙏 发自我的 iPhone在 2024年10月24日，00:36，xingyushu ***@***.***> 写道：﻿

Does anyone have this corpus database？Could you please send me a copy? Thx. My email address is: ***@***.***

did you get the dataset
