### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by cat-6sephiruth** [ebagdasa/backdoor_federated_learning#5]
If I try, the following errors occur.
==>
RuntimeError: result type Float can't be cast to the desired output type Long

I'm still a beginner, so I'm having a lot of trouble.
![image](https://user-images.githubusercontent.com/13704709/76823350-4eb2b700-6857-11ea-87aa-fb028541c824.png)

**Comment by adarshku7** [comment]
can you tell me how you resolved this issue ?

**Comment by cat-6sephiruth** [comment]
Hello, as far as I remember, if you forced it to form (float) roughly, the code would have been returned without any problems.
 
If you can't solve the problem, please email me later and I will help you.
***@***.*** This is my main e-mail.
 





 
-----Original Message-----
