### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by shiwen1997** [ebagdasa/backdoor_federated_learning#8]
thank you for your code firstly.
How long does this code take to run? when I run "python training.py --params utils/params.yaml", it keep log err:
![RPP$ UBF1B3BB{Y{JWEP7B5](https://user-images.githubusercontent.com/49514954/84853618-26269d00-b092-11ea-8400-37f512b0e38a.png)

**Comment by ebagdasa** [comment]
looks like visdom is not started.
